# Each letter represent a colour marker: k, r, g, y, b, m, c, w
# which stands for:    blacK, Red, Green, Yellow, Blue, Magenta,Cyan, White
# Capital letters makes bold fonts

Keyword = "y"
Name = "W"
Comment = "b"
String = "m"
Error = "r"
Literal = "r"
LiteralString = "m"
TokenLiteralNumberFloat = "G"
Number = "g"
Operator = "C"
OperatorWord = "C"
Punctuation = "C"
Generic = "b"
Token = "g"
Whitespace = "D"

