# Each letter represent a colour marker: k, r, g, y, b, m, c, w
# which stands for:    blacK, Red, Green, Yellow, Blue, Magenta,Cyan, White
# Capital letters makes bold fonts
# Copy to ~/.bpython/foo.theme and set "color_scheme = foo" in ~/.bpython.ini

[syntax]
keyword = y
name = c
comment = b
string = m
error = r
number = G
operator = Y
punctuation = y
token = C

[interface]
background = k
output = w
main = c
prompt = c
prompt_more = g
