.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BPYTHON-CONFIG 5 "September 21, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
config \- user configuration file for bpython
.SH SYNOPSIS
.B $XDG_CONFIG_HOME/bpython/config
.B ~/.bpython/config
.SH DESCRIPTION
The 
.B config
contains various options controlling the behaviour of \fBbpython\fR.

See http://docs.bpython-interpreter.org/configuration.html for a full
description of the configuration file.

.SH AUTHOR
bpython was written by Robert Anthony Farrell <robertanthonyfarrel@gmail.com> and his bunch of loyal followers.
.PP
This manual page was written by Jørgen Pedersen Tjernø <jorgen@devsoft.no>,
for the Debian project (but may be used by others).
