from .events import FileSystemEventHandler

class Observer:
    def start(self): ...
    def schedule(
        self, observer: FileSystemEventHandler, dirname: str, recursive: bool
    ): ...
    def unschedule_all(self): ...
